# Generated by Django 2.2.12 on 2021-10-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perception', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='sexual_assualt',
        ),
        migrations.AddField(
            model_name='crime',
            name='sexual_assault',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='street_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='attempted_murder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='damage_to_property',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='drunk_driving',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='shoplifting',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='vehicle_theft',
            field=models.IntegerField(null=True),
        ),
    ]
